inherit_from: .rubocop_todo.yml

# Turn on RSpec cops
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - Gemfile.lock
    - '**/*.md'
    - 'vendor/**/*' # avoid running rubocop on travis cached bundler

# --- Layout ---

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/LineLength:
  Max: 183 # this isn't 1994; FIXME: would like to get this down to 120

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

# --- Lint ---

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

# --- Metrics ---

Metrics/BlockLength:
  Exclude:
    - spec/**/*

# --- Naming ---

Naming/FileName:
  Exclude:
    - Capfile
    - Gemfile

Naming/MethodName:
  Exclude:
    - lib/robots/dor_repo/gis_assembly/generate_geo_metadata.rb # to_geoMetadataDS

# --- Performance ---

# --- RSpec ---

RSpec/ExampleLength:
    Enabled: false

# --- Style ---

Style/IfUnlessModifier:
  Enabled: false
    # robots/gisAssembly/extract-boundingbox.rb # line 233 unless ulx <= lrx && uly >= lry
    # robots/gisDiscovery/export-opengeometadata.rb # line 72 if xml.nil? || xml.root.nil?

Style/StringLiterals:
  Enabled: false # ' vs " isn't a big deal for readability or maintainability or execution time

Style/SymbolArray:
  Exclude:
    - Rakefile # because [:spec, :rubocop] isn't a big deal

Style/RedundantFetchBlock:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/StringConcatenation:
  Enabled: true
