version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@3.2.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
          context: dlss
          executor:
            name: ruby-rails/ruby
            ruby-tag: '3.2.2'
      - ruby-rails/test-gem:
          name: test
          context: dlss
          executor:
            name: ruby-rails/ruby
            ruby-tag: '3.2.2'
