version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@4.0.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
          context: dlss
      - ruby-rails/test-gem:
          name: test
          context: dlss
