version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@4.2.1
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
          context: dlss
      - ruby-rails/test-gem:
          name: test
          context: dlss
          before-test:
            - run: sudo apt-get update -y
            - run: sudo apt-get install -y xsltproc libxml2-utils gdal-bin
