# frozen_string_literal: true

require 'spec_helper'

RSpec.describe Robots::DorRepo::GisDerivative::CreateDerivatives do
  subject(:perform) { test_perform(robot, druid) }

  let(:bare_druid) { druid.delete_prefix('druid:') }
  let(:robot) { described_class.new }
  let(:cocina_object) { build(:dro, id: druid).new(structural: structural, access: { view: 'world' }) }
  let(:object_client) do
    instance_double(Dor::Services::Client::Object, find: cocina_object, update: true)
  end
  let(:workspace_path) { Pathname.new(Settings.geohydra.workspace) / bare_druid[0..1] / bare_druid[2..4] / bare_druid[5..6] / bare_druid[7..] / bare_druid / 'content' }
  let(:structural) { Cocina::Models::DROStructural.new({ contains: [fileset] }) }
  let(:fileset) do
    Cocina::Models::FileSet.new(
      type: 'https://cocina.sul.stanford.edu/models/resources/object',
      externalIdentifier: "https://cocina.sul.stanford.edu/fileSet/#{bare_druid}-#{bare_druid}_1",
      label: 'Data',
      version: 2,
      structural: { contains: files }
    )
  end
  let(:files) { [master_file] }
  let(:jp2_file_path) { workspace_path / "#{layer_name}.jp2" }

  before do
    allow(robot).to receive(:druid).and_return(druid)
    allow(Dor::Services::Client).to receive(:object).and_return(object_client)
    allow(GisRobotSuite).to receive(:locate_druid_path).and_return(workspace_path.parent)
    perform
  end

  after do
    FileUtils.rm_f(jp2_file_path)
    FileUtils.rm_f(jp2_file_path.sub_ext('.jp2.aux.xml')) # Remove unused generated auxiliary file
  end

  context 'with a raster (geotiff)' do
    let(:druid) { 'druid:bb021mm7809' }
    let(:layer_name) { 'MCE_FI2G_2014' }
    let(:master_file) do
      Cocina::Models::File.new(
        type: 'https://cocina.sul.stanford.edu/models/file',
        externalIdentifier: "https://cocina.sul.stanford.edu/file/#{bare_druid}-#{bare_druid}_1/#{layer_name}.tif",
        label: "#{layer_name}.tif",
        filename: "#{layer_name}.tif",
        size: 100,
        version: 2,
        hasMimeType: 'image/tiff; application=geotiff',
        use: 'master',
        administrative: {
          publish: true,
          sdrPreserve: true,
          shelve: true
        }
      )
    end
    let(:cog_file_path) { workspace_path / "#{layer_name}_cog.tif" }

    after do
      FileUtils.rm_f(cog_file_path)
      FileUtils.rm_f(jp2_file_path)
    end

    it 'creates a COG' do
      expect(cog_file_path).to exist
    end

    it 'creates a JP2 thumbnail' do
      expect(jp2_file_path).to exist
    end

    it 'updates structural metadata' do
      expect(object_client).to have_received(:update) do |params:|
        new_contains = params.structural.contains.first.structural.contains
        expect(new_contains.count).to eq 3
        expect(new_contains.map(&:use)).to eq %w[master derivative thumbnail]
        jp2_file = new_contains.find { |f| f.use == 'thumbnail' }
        expect(jp2_file.hasMimeType).to eq 'image/jp2'
        expect(jp2_file.presentation.height).to eq 7435
        expect(jp2_file.presentation.width).to eq 10503
      end
    end

    context 'when the COG already exists in cocina' do
      let(:files) { [master_file, derivative_file] }
      let(:derivative_file) do
        Cocina::Models::File.new(
          type: 'https://cocina.sul.stanford.edu/models/file',
          externalIdentifier: "https://cocina.sul.stanford.edu/file/#{bare_druid}-#{bare_druid}_1/#{layer_name}_cog.tif",
          label: "#{layer_name}_cog.tif",
          filename: "#{layer_name}_cog.tif",
          size: 50,
          version: 2,
          hasMimeType: 'image/tiff; application=geotiff; profile=cloud-optimized',
          use: 'derivative',
          sdrGeneratedText: sdr_generated_text,
          administrative: {
            publish: true,
            sdrPreserve: false,
            shelve: true
          }
        )
      end

      context 'when the existing COG was generated by SDR' do
        let(:sdr_generated_text) { true }

        it 'replaces the derivative and adds a thumbnail' do
          expect(object_client).to have_received(:update) do |params:|
            new_contains = params.structural.contains.first.structural.contains
            expect(new_contains.count).to eq 3
            expect(new_contains.map(&:use)).to eq %w[master derivative thumbnail]
            # Ensure the old derivative was removed and a new one added (new externalIdentifier)
            expect(new_contains.find { |f| f.hasMimeType.include?('profile=cloud-optimized') }.externalIdentifier).not_to eq derivative_file.externalIdentifier
          end
        end
      end

      context 'when the existing COG was not generated by SDR' do
        let(:sdr_generated_text) { false }

        it 'retains the original derivative and adds a thumbnail' do
          expect(object_client).to have_received(:update) do |params:|
            new_contains = params.structural.contains.first.structural.contains
            expect(new_contains.count).to eq 3
            expect(new_contains.map(&:use)).to eq %w[master derivative thumbnail]
            # Ensure the old derivative was retained (same externalIdentifier)
            expect(new_contains.find { |f| f.hasMimeType.include?('profile=cloud-optimized') }.externalIdentifier).to eq derivative_file.externalIdentifier
          end
        end
      end
    end
  end

  context 'with vectors' do
    let(:fgb_file_path) { workspace_path / "#{layer_name}.fgb" }
    let(:pmtiles_file_path) { workspace_path / "#{layer_name}.pmtiles" }

    after do
      FileUtils.rm_f(fgb_file_path)
      FileUtils.rm_f(pmtiles_file_path)
    end

    context 'with a shapefile' do
      let(:druid) { 'druid:cc044gt0726' }
      let(:layer_name) { 'sanluisobispo1996' }
      let(:master_file) do
        Cocina::Models::File.new(
          type: 'https://cocina.sul.stanford.edu/models/file',
          externalIdentifier: "https://cocina.sul.stanford.edu/fileSet/#{bare_druid}-#{bare_druid}_1/#{layer_name}.shp",
          label: "#{layer_name}.shp",
          filename: "#{layer_name}.shp",
          size: 100,
          version: 2,
          hasMimeType: 'application/vnd.shp',
          use: 'master',
          administrative: {
            publish: true,
            sdrPreserve: true,
            shelve: true
          }
        )
      end

      it 'creates a FlatGeoBuf' do
        expect(fgb_file_path).to exist
      end

      it 'creates a PMTiles archive' do
        expect(pmtiles_file_path).to exist
      end

      it 'creates a JP2 thumbnail' do
        expect(jp2_file_path).to exist
      end

      it 'updates structural metadata' do
        expect(object_client).to have_received(:update) do |params:|
          new_contains = params.structural.contains.first.structural.contains
          expect(new_contains.count).to eq 4
          expect(new_contains.map(&:use)).to eq %w[master derivative derivative thumbnail]
          expect(new_contains.map(&:hasMimeType)).to contain_exactly('application/vnd.shp', 'application/vnd.fgb', 'application/vnd.pmtiles', 'image/jp2')
          jp2_file = new_contains.find { |f| f.use == 'thumbnail' }
          expect(jp2_file.presentation.height).to eq 512
          expect(jp2_file.presentation.width).to eq 512
        end
      end

      context 'with mixed single/multi geometry type' do
        let(:druid) { 'druid:cz128vq0535' }
        let(:layer_name) { 'Ug_Rural_Poverty2005' }

        it 'successfully creates the FlatGeoBuf and PMTile by promoting to multi' do
          perform
          expect(fgb_file_path).to exist
          expect(pmtiles_file_path).to exist
        end
      end

      context 'with features that have invalid geometry' do
        let(:druid) { 'druid:cq376yf4339' }
        let(:layer_name) { 'BIO_CA_Mammal_Pinnipeds_Haulouts_MLPAcompilation' }

        it 'successfully creates the FlatGeoBuf and PMTiles archive by dropping invalid geometries' do
          perform
          expect(fgb_file_path).to exist
          expect(pmtiles_file_path).to exist
        end
      end

      context 'when the derivatives already exist in cocina' do
        let(:files) { [master_file, derivative_fgb_file, derivative_pmtiles_file] }
        let(:derivative_fgb_file) do
          Cocina::Models::File.new(
            type: 'https://cocina.sul.stanford.edu/models/file',
            externalIdentifier: "https://cocina.sul.stanford.edu/file/#{bare_druid}-#{bare_druid}_1/#{layer_name}.fgb",
            label: "#{layer_name}.fgb",
            filename: "#{layer_name}.fgb",
            size: 50,
            version: 2,
            hasMimeType: 'application/vnd.fgb',
            use: 'derivative',
            sdrGeneratedText: sdr_generated_text,
            administrative: { publish: true, sdrPreserve: false, shelve: true }
          )
        end

        let(:derivative_pmtiles_file) do
          Cocina::Models::File.new(
            type: 'https://cocina.sul.stanford.edu/models/file',
            externalIdentifier: "https://cocina.sul.stanford.edu/file/#{bare_druid}-#{bare_druid}_1/#{layer_name}.pmtiles",
            label: "#{layer_name}.pmtiles",
            filename: "#{layer_name}.pmtiles",
            size: 50,
            version: 2,
            hasMimeType: 'application/vnd.pmtiles',
            use: 'derivative',
            sdrGeneratedText: sdr_generated_text,
            administrative: { publish: true, sdrPreserve: false, shelve: true }
          )
        end

        context 'when the derivatives were generated by SDR' do
          let(:sdr_generated_text) { true }

          it 'replaces all derivatives' do
            expect(object_client).to have_received(:update) do |params:|
              new_contains = params.structural.contains.first.structural.contains
              expect(new_contains.count).to eq 4
              # Ensure the old derivatives were removed and new ones added
              expect(new_contains.count { |f| f.use == 'derivative' }).to eq 2
              expect(new_contains.count { |f| f.use == 'thumbnail' }).to eq 1
              derivatives = new_contains.select { |f| f.use == 'derivative' }
              expect(derivatives.map(&:externalIdentifier)).not_to include(derivative_fgb_file.externalIdentifier)
              expect(derivatives.map(&:externalIdentifier)).not_to include(derivative_pmtiles_file.externalIdentifier)
              expect(derivatives.map(&:hasMimeType)).to contain_exactly('application/vnd.fgb', 'application/vnd.pmtiles')
              expect(new_contains.find { |f| f.use == 'thumbnail' }.hasMimeType).to eq 'image/jp2'
            end
          end
        end

        context 'when the derivatives were not generated by SDR' do
          let(:sdr_generated_text) { false }

          it 'retains all derivatives' do
            expect(object_client).to have_received(:update) do |params:|
              new_contains = params.structural.contains.first.structural.contains
              expect(new_contains.count).to eq 4
              # Ensure the old derivatives were preserved
              expect(new_contains.count { |f| f.use == 'derivative' }).to eq 2
              expect(new_contains.count { |f| f.use == 'thumbnail' }).to eq 1
              derivatives = new_contains.select { |f| f.use == 'derivative' }
              expect(derivatives.map(&:externalIdentifier)).to include(derivative_fgb_file.externalIdentifier)
              expect(derivatives.map(&:externalIdentifier)).to include(derivative_pmtiles_file.externalIdentifier)
              expect(derivatives.map(&:hasMimeType)).to contain_exactly('application/vnd.fgb', 'application/vnd.pmtiles')
              expect(new_contains.find { |f| f.use == 'thumbnail' }.hasMimeType).to eq 'image/jp2'
            end
          end
        end
      end
    end

    context 'with geojson' do
      let(:druid) { 'druid:yt111kw1413' }
      let(:layer_name) { 'samTrans_bus_routes_20151021_shapes_20260406' }
      let(:master_file) do
        Cocina::Models::File.new(
          type: 'https://cocina.sul.stanford.edu/models/file',
          externalIdentifier: "https://cocina.sul.stanford.edu/file/#{bare_druid}-#{bare_druid}_1/#{layer_name}.geojson",
          label: "#{layer_name}.geojson",
          filename: "#{layer_name}.geojson",
          size: 100,
          version: 2,
          hasMimeType: 'application/geo+json',
          use: 'master',
          administrative: {
            publish: true,
            sdrPreserve: true,
            shelve: true
          }
        )
      end

      it 'creates a FlatGeoBuf' do
        expect(fgb_file_path).to exist
      end

      it 'creates a PMTiles archive' do
        expect(pmtiles_file_path).to exist
      end

      it 'creates a JP2 thumbnail' do
        expect(jp2_file_path).to exist
      end

      it 'updates structural metadata' do
        expect(object_client).to have_received(:update) do |params:|
          new_contains = params.structural.contains.first.structural.contains
          expect(new_contains.count).to eq 4
          expect(new_contains.map(&:use)).to eq %w[master derivative derivative thumbnail]
          expect(new_contains.map(&:hasMimeType)).to contain_exactly('application/geo+json', 'application/vnd.fgb', 'application/vnd.pmtiles', 'image/jp2')
          jp2_file = new_contains.find { |f| f.use == 'thumbnail' }
          expect(jp2_file.presentation.height).to eq 512
          expect(jp2_file.presentation.width).to eq 512
        end
      end
    end
  end
end
