connection_error_max_retries: 3

dor_services:
  url:  'https://dor-services-test.stanford.test'
  token: secret-token

geohydra:
  stage: '/stage'
  workspace: '/workspace'
  tmpdir: '/tmp'
  opengeometadata:
    dir: '/opengeometadata'

purl:
  url: 'http://localhost/purl'

gdal_path: ''
