#
#  Robot allocation strategy
#
#  Format:
#
#    host:
#      - robot[:lane[:instances]]
#
#  where
#    1. robot is a single robot identifier (fully-qualified with
#       REPO_SUITE_ROBOT, e.g., "dor_accessionWF_technical-metadata").
#    2. lane is 
#          - a single identifier ('A'), or 
#          - a list of identiers ('A,B,C'), or 
#          - an asterix (*).
#    3. instances is a single integer.
#
#  Both lane and instances are optional. Lane defaults to 'default', and 
#  instances defaults to 1.
#
#  When a robot is allocated to multiple lanes, it reads them in
#  PRIORITY ORDER. That is, if a robot is listening to lanes A, B, and C,
#  it works on lane A until empty, then lane B until empty, and then
#  lane C until empty. In the meantime, if a job comes in on a 'faster'
#  lane, it works on that after finishing it's current job (i.e., after
#  working on a job in lane C, if a job comes in on lane A in the intermin,
#  the robot will work on the lane A job next before returning to lane C).
#  When using an asterix for the lane designator, the lanes are processed
#  in alphabetical order.
#
#  Note that the syntax is YAML, so the lists must not contain spaces or
#  needs to be quoted.
#  
#    RIGHT
#      - dor_accessionWF_technical-metadata:A:5
#      - 'dor_accessionWF_technical-metadata : A : 5'
#
#    WRONG
#      - dor_accessionWF_technical-metadata : A : 5
#      - dor_accessionWF_technical-metadata: A: 5
#

sul-robots1-dev:
  - dor_myDemoWF_a1-first:default:3 # 3 robots in default lane
  - dor_myDemoWF_b2-second          # 1 robot in default lane
  - dor_myDemoWF_c3-third:myLane    # 1 robot in myLane lane

sul-robots2-dev:
  - dor_myDemoWF_a1-first:*         # 1 robot in all lanes
  - dor_myDemoWF_b2-second:default,myLane # 1 robot in default and myLane lanes
  - dor_myDemoWF_c3-third:*:3       # 3 robots in all lanes
